import type { CodeThemeOption } from "./types";

export const BUILT_IN_THEMES: CodeThemeOption[] = [
	// ── Dark themes ──
	{
		id: "vitesse-black",
		name: "Vitesse Black",
		type: "built-in",
		mode: "dark",
		bgColor: "#000000",
		fgColor: "#dbd7ca",
		accentColor: "#4d9375",
	},
	{
		id: "github-dark",
		name: "GitHub Dark",
		type: "built-in",
		mode: "dark",
		bgColor: "#0d1117",
		fgColor: "#e6edf3",
		accentColor: "#79c0ff",
	},
	{
		id: "github-dark-dimmed",
		name: "GitHub Dimmed",
		type: "built-in",
		mode: "dark",
		bgColor: "#22272e",
		fgColor: "#adbac7",
		accentColor: "#6cb6ff",
	},
	{
		id: "dracula",
		name: "Dracula",
		type: "built-in",
		mode: "dark",
		bgColor: "#282a36",
		fgColor: "#f8f8f2",
		accentColor: "#bd93f9",
	},
	{
		id: "one-dark-pro",
		name: "One Dark Pro",
		type: "built-in",
		mode: "dark",
		bgColor: "#282c34",
		fgColor: "#abb2bf",
		accentColor: "#c678dd",
	},
	{
		id: "tokyo-night",
		name: "Tokyo Night",
		type: "built-in",
		mode: "dark",
		bgColor: "#1a1b26",
		fgColor: "#a9b1d6",
		accentColor: "#7aa2f7",
	},
	{
		id: "nord",
		name: "Nord",
		type: "built-in",
		mode: "dark",
		bgColor: "#2e3440",
		fgColor: "#d8dee9",
		accentColor: "#88c0d0",
	},
	{
		id: "catppuccin-mocha",
		name: "Catppuccin Mocha",
		type: "built-in",
		mode: "dark",
		bgColor: "#1e1e2e",
		fgColor: "#cdd6f4",
		accentColor: "#cba6f7",
	},
	{
		id: "ayu-dark",
		name: "Ayu Dark",
		type: "built-in",
		mode: "dark",
		bgColor: "#0b0e14",
		fgColor: "#bfbdb6",
		accentColor: "#e6b450",
	},
	{
		id: "monokai",
		name: "Monokai",
		type: "built-in",
		mode: "dark",
		bgColor: "#272822",
		fgColor: "#f8f8f2",
		accentColor: "#f92672",
	},
	{
		id: "solarized-dark",
		name: "Solarized Dark",
		type: "built-in",
		mode: "dark",
		bgColor: "#002b36",
		fgColor: "#839496",
		accentColor: "#268bd2",
	},

	// ── Light themes ──
	{
		id: "vitesse-light",
		name: "Vitesse Light",
		type: "built-in",
		mode: "light",
		bgColor: "#ffffff",
		fgColor: "#393a34",
		accentColor: "#1e754f",
	},
	{
		id: "github-light",
		name: "GitHub Light",
		type: "built-in",
		mode: "light",
		bgColor: "#ffffff",
		fgColor: "#1f2328",
		accentColor: "#0550ae",
	},
	{
		id: "one-light",
		name: "One Light",
		type: "built-in",
		mode: "light",
		bgColor: "#fafafa",
		fgColor: "#383a42",
		accentColor: "#a626a4",
	},
	{
		id: "catppuccin-latte",
		name: "Catppuccin Latte",
		type: "built-in",
		mode: "light",
		bgColor: "#eff1f5",
		fgColor: "#4c4f69",
		accentColor: "#8839ef",
	},
	{
		id: "solarized-light",
		name: "Solarized Light",
		type: "built-in",
		mode: "light",
		bgColor: "#fdf6e3",
		fgColor: "#657b83",
		accentColor: "#268bd2",
	},
	{
		id: "min-light",
		name: "Min Light",
		type: "built-in",
		mode: "light",
		bgColor: "#ffffff",
		fgColor: "#24292eff",
		accentColor: "#1a1a1a",
	},
];

export function getBuiltInTheme(id: string): CodeThemeOption | undefined {
	return BUILT_IN_THEMES.find((t) => t.id === id);
}

export function getBuiltInThemesByMode(mode: "dark" | "light"): CodeThemeOption[] {
	return BUILT_IN_THEMES.filter((t) => t.mode === mode);
}
